version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      tokio:
        patterns:
          - "tokio*"
      tracing:
        patterns:
          - "tracing*"
      rustls:
        patterns:
          - "rustls*"
          - "tokio-rustls*"
          - "rustls-pemfile*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
