[package]
name = "zetmq-client"
version.workspace = true
edition.workspace = true

[dependencies]
zetmq-protocol = { path = "../zetmq-protocol" }
tokio.workspace = true
bytes.workspace = true
thiserror.workspace = true
rand = "0.8"
tracing.workspace = true
tokio-rustls = "0.26"
rustls-pemfile = "2"
rustls-native-certs = "0.8"
rustls = { version = "0.23", features = ["ring"] }
