[package]
name = "zetmq-client"
description = "Async client library for ZetMQ message broker"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
zetmq-protocol = { version = "0.2.3", path = "../zetmq-protocol" }
tokio.workspace = true
bytes.workspace = true
thiserror.workspace = true
rand = "0.10"
tracing.workspace = true
tokio-rustls = "0.26"
rustls-pemfile = "2"
rustls-native-certs = "0.8"
rustls = { version = "0.23", features = ["ring"] }
